import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/home/navbar";
import { navLinks } from "@/constants/nav-link";
import { ThemeProvider } from "@/components/global/theme-provider";
import { fontMontserrat } from "@/config/fonts";
import { Providers } from "@/lib/providers";
import { Toaster } from "@/components/ui/sonner";
import { GlobalModal } from "@/components/global/modal/global-modal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${fontMontserrat.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            <div className="relative flex flex-col h-screen">
              <Navbar links={navLinks} />
              <GlobalModal />

              <main>
                <Toaster richColors position="top-right" />
                {children}
              </main>
            </div>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
